### ISSUE TITLE
Error Reporting in Walk In Center

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/cardswipr#78]
The `/swipe` page has a clever and helpful error when someone isn't found, like "Could not find UPI for 123456789". The Walk In Center page doesn't have that same error, and it should.

This happened because of non-DRY code. I think the app would be better if there were maybe just two views of an "event" that shared a controller. This is part of a bigger issue, that WCSses want to keep a log of all people who go to a location (see issue #46).

**Comment by gigamorph** [comment]
They now have shared "flash" of error messages with a code number. The message is deliberately simple. More details are printed to the server log.
