### ISSUE TITLE
New ID Card Latency

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/cardswipr#81]
When someone gets a New ID card, that won't work in CardSwipr until our data source is updated, which may not be frequently right now. We should ask Bill Horowitz and the API Portal team how often the data source it is updated. 

We can either:
- work with ITS to either make this more frequent (better for clients)
- publish/publicize the refresh rate to event admins (but realistically they probably won't read this no matter where we put it :/)

**Comment by orenyk** [comment]
Closing to clean up our issue queue.
