### ISSUE TITLE
Security Design Review

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/cardswipr#83]
Yale has a formal process called the "Security Design Review" that we should do for all of our applications. We've gone through their intake survey once and we have a number of to-do's. Most of the issues in this milestones are prerequisites for us announcing this application and going live.

This issue will mostly be done outside of Github Issues, by @jeminlee in person with Yale Information Security. Issues that require development work on this issue will each have an issue created in this milestone.

**Comment by gigamorph** [comment]
The rails application server part passed the SDR. Remedial work on the infrastructure (hosting server) is under way.

**Comment by caseywatts** [comment]
this is wonderful news, yayy! :D
:tada:

**Comment by orenyk** [comment]
Closing to clean up our issue queue.
