### ISSUE TITLE
Announce CardSwipr

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/cardswipr#84]
When we're ready, we should announce this to Yale!
- [ ] Monday Morning News Article
- [ ] Yammer
- [ ] Email someone in each major department we work with something describing the service and ask them to spread the word.
- [ ] Email directly those interested people whose names we have in a list / our current beta-testing users

**Comment by hydrosquall** [comment]
The UI is looking really cool, props to the team that's bringing this to life :)
