### ISSUE TITLE
Use new CARDSwipr API

### ISSUE THREAD

**Issue by gigamorph** [YaleSTC/cardswipr#85]
Replace existing look-ups (YaleLDAP, idcardslookup API)  with the new CARDSwipr API.

**Comment by gigamorph** [comment]
A  problem: with the old "idcardlookup" API(did it ever exist?), it doesn't distinguish between a mag-stripe number and a prox card number. The API would just take a 10-digit number. With the new API(cardswipr), we have to provide either "magstripenumber" or "proxNumber" as key for the query. 

The best case would be if there's a way for the card reader to produce a differentiating string, e.g., "prox:1234567890" or "mag:1234567890". Otherwise we will either have to ask to modify the API or assume prox numbers and mag numbers don't overlap and make two requests for each input.

**Comment by caseywatts** [comment]
As of last January, the ITS server that stores both types of data were in the same database table - both types of IDs are in the same column, and a separate column states which type it is. Are these databases being split out?

[Bill Horowitz](http://directory.yale.edu/?queryType=field&upi=10250886) can probably say what the patterns are. I believe (at least so far) the ID numbers don't ever overlap. They do happen to follow some kind of predictable pattern so far too, that may help.

**Comment by gigamorph** [comment]
Done.
